import SwiftUI

enum AppLanguage: String, CaseIterable, Identifiable {
    case pirate = "pirate"
    case english = "en"
    case chinese = "zh"
    case spanishLA = "es_419"
    case spanishES = "es_ES"
    case hindi = "hi"
    case telugu = "te"
    case french = "fr"
    case italian = "it"
    case portuguese = "pt"
    case romanian = "ro"
    case japanese = "ja"
    case korean = "ko"
    case vietnamese = "vi"
    case tagalog = "tl"
    case thai = "th"
    
    var id: String { rawValue }
    
    var displayName: String {
        switch self {
        case .pirate:      return "🏴‍☠️ Pirate Speak"
        case .english:     return "🇺🇸 English"
        case .chinese:     return "🇨🇳 中文 (Simplified)"
        case .spanishLA:   return "🇲🇽 Español (LatAm)"
        case .spanishES:   return "🇪🇸 Español (Castellano)"
        case .hindi:       return "🇮🇳 हिन्दी (Hindi)"
        case .telugu:      return "🇮🇳 తెలుగు (Telugu)"
        case .french:      return "🇫🇷 Français"
        case .italian:     return "🇮🇹 Italiano"
        case .portuguese:  return "🇵🇹 Português"
        case .romanian:    return "🇷🇴 Română"
        case .japanese:    return "🇯🇵 日本語"
        case .korean:      return "🇰🇷 한국어"
        case .vietnamese:  return "🇻🇳 Tiếng Việt"
        case .tagalog:     return "🇵🇭 Tagalog"
        case .thai:        return "🇹🇭 ภาษาไทย"
        }
    }
}

class LanguageManager: ObservableObject {
    static let shared = LanguageManager()
    
    @Published var currentLanguage: AppLanguage = .pirate
    
    func translate(_ key: String) -> String {
        return translations[key]?[currentLanguage] ?? translations[key]?[.english] ?? key
    }
    
    func translate(_ key: String, for language: AppLanguage) -> String {
        return translations[key]?[language] ?? translations[key]?[.english] ?? key
    }
    
    private let translations: [String: [AppLanguage: String]] = [
        "lang_title": [
            .pirate: "Choose Your\nTongue",
            .english: "Select Your\nLanguage",
            .chinese: "选择您的\n语言",
            .spanishLA: "Selecciona tu\nIdioma",
            .spanishES: "Elige tu\nIdioma",
            .hindi: "अपनी भाषा\nचुनें",
            .telugu: "మీ భాషను\nఎంచుకోండి",
            .french: "Choisissez votre\nLangue",
            .italian: "Scegli la tua\nLingua",
            .portuguese: "Escolha seu\nIdioma",
            .romanian: "Alegeți\nLimba",
            .japanese: "言語を\n選択する",
            .korean: "언어를\n선택하세요",
            .vietnamese: "Chọn\nNgôn Ngữ",
            .tagalog: "Pumili ng\nWika",
            .thai: "เลือก\nภาษาของคุณ"
        ],
        "lang_desc": [
            .pirate: "Select your native tongue before we set sail on this voyage, Captain.",
            .english: "Select your preferred language before we configure your setup.",
            .chinese: "在配置设置之前选择您首选的语言。",
            .spanishLA: "Selecciona tu idioma preferido antes de configurar la aplicación.",
            .spanishES: "Selecciona tu idioma de preferencia antes de configurar el sistema.",
            .hindi: "सेटअप कॉन्फ़िगर करने से पहले अपनी पसंद की भाषा चुनें।",
            .telugu: "సెటప్‌ను కాన్ఫిగర్ చేయడానికి ముందు మీ ప్రాధాన్య భాషను ఎంచుకోండి.",
            .french: "Sélectionnez votre langue préférée avant de configurer vos paramètres.",
            .italian: "Seleziona la tua lingua preferita prima di configurare le impostazioni.",
            .portuguese: "Selecione seu idioma preferido antes de configurar seus parâmetros.",
            .romanian: "Selectați limba preferată înainte de a vă configura setările.",
            .japanese: "設定を構成する前に、お好みの言語を選択してください。",
            .korean: "설정을 구성하기 전에 선호하는 언어를 선택하세요.",
            .vietnamese: "Chọn ngôn ngữ ưu tiên của bạn trước khi cấu hình thiết lập.",
            .tagalog: "Pumili ng gusto mong wika bago natin i-configure ang iyong setup.",
            .thai: "เลือกภาษาที่คุณต้องการก่อนเริ่มตั้งค่าระบบ"
        ],
        "lang_btn": [
            .pirate: "Confirm Tongue",
            .english: "Confirm Language",
            .chinese: "确认语言",
            .spanishLA: "Confirmar Idioma",
            .spanishES: "Confirmar Idioma",
            .hindi: "भाषा की पुष्टि करें",
            .telugu: "భాషను నిర్ధారించండి",
            .french: "Confirmer la langue",
            .italian: "Conferma lingua",
            .portuguese: "Confirmar idioma",
            .romanian: "Confirmați limba",
            .japanese: "言語を決定する",
            .korean: "언어 확인",
            .vietnamese: "Xác nhận Ngôn ngữ",
            .tagalog: "Kumpirmahin ang Wika",
            .thai: "ยืนยันภาษา"
        ],
        "welcome_title": [
            .pirate: "Drop\nAnchor",
            .english: "Drop\nAnchor",
            .chinese: "放下\n锚点",
            .spanishLA: "Echar\nAncla",
            .spanishES: "Echar\nAncla",
            .hindi: "लंगर\nडालें",
            .telugu: "యాంకర్\nవేయండి",
            .french: "Jeter\nl'Ancre",
            .italian: "Getta\nl'Ancora",
            .portuguese: "Lançar\nÂncora",
            .romanian: "Aruncă\nAncora",
            .japanese: "アンカーを\n下ろす",
            .korean: "닻을\n내리다",
            .vietnamese: "Thả\nNeo",
            .tagalog: "Ihulog ang\nAnchor",
            .thai: "ทิ้ง\nสมอ"
        ],
        "welcome_desc": [
            .pirate: "Preserve your focus momentum. Anchored watches your active applications and gently drops anchor when you drift into distracting waters.",
            .english: "Preserve your focus momentum. Anchored monitors your active applications and gently blocks access when you drift into distracting websites or apps.",
            .chinese: "保持您的专注动力。Anchored 会监控您当前活跃的应用程序，并在您分心使用其他应用或网页时自动拦截。",
            .spanishLA: "Mantén tu enfoque. Anchored supervisa tus aplicaciones activas y bloquea el acceso con suavidad cuando te desvías hacia sitios o aplicaciones de distracción.",
            .spanishES: "Preserva el impulso de tu concentración. Anchored monitoriza tus aplicaciones activas y bloquea el acceso de forma sutil cuando te distraes.",
            .hindi: "अपने फोकस की गति को बनाए रखें। Anchored आपके सक्रिय ऐप्स पर नज़र रखता है और ध्यान भटकाने वाले ऐप्स पर जाने पर धीरे से पहुंच को रोकता है।",
            .telugu: "మీ ఏకాగ్రత వేగాన్ని కాపాడుకోండి. యాంకర్డ్ మీ క్రియాశీల అప్లికేషన్‌లను పర్యవేక్షిస్తుంది మరియు మీరు దృష్టిని మరల్చే యాప్‌లకు వెళ్ళినప్పుడు యాక్సెస్‌ను సున్నితంగా నిరోధిస్తుంది.",
            .french: "Préservez votre élan de concentration. Anchored surveille vos applications actives et bloque doucement l'accès lorsque vous dérivez vers des distractions.",
            .italian: "Mantieni alta la concentrazione. Anchored monitora le tue applicazioni attive e blocca l'accesso con delicatezza quando ti lasci distrarre.",
            .portuguese: "Preserve seu foco. O Anchored monitora seus aplicativos ativos e bloqueia o acesso gentilmente quando você se perde em distrações.",
            .romanian: "Mențineți-vă concentrarea. Anchored vă monitorizează aplicațiile active și vă blochează accesul atunci când vă distrageți atenția.",
            .japanese: "集中力を維持します。Anchoredはアクティブなアプリケーションを監視し、気を散らすアプリやウェブサイトに流されたときにアクセスを優しく制限します。",
            .korean: "집중력을 유지하세요. Anchored는 실행 중인 앱을 모니터링하여 집중을 방해하는 앱이나 웹사이트로 벗어날 때 액세스를 차단합니다.",
            .vietnamese: "Giữ vững đà tập trung của bạn. Anchored theo dõi các ứng dụng đang hoạt động và nhẹ nhàng chặn truy cập khi bạn sa đà vào các ứng dụng gây xao nhãng.",
            .tagalog: "Panatilihin ang iyong konsentrasyon. Binabantayan ng Anchored ang iyong mga aktibong app at hinaharangan ang access kapag nalilihis ka sa mga distraction.",
            .thai: "รักษาความต่อเนื่องในการทำงานของคุณ Anchored จะคอยเฝ้าดูการใช้งานแอปพลิเคชันและช่วยบล็อกการเข้าถึงเมื่อคุณเริ่มเสียสมาธิไปกับแอปอื่น"
        ],
        "welcome_btn": [
            .pirate: "Embark",
            .english: "Get Started",
            .chinese: "开始使用",
            .spanishLA: "Comenzar",
            .spanishES: "Comenzar",
            .hindi: "शुरू करें",
            .telugu: "ప్రారంభించండి",
            .french: "Commencer",
            .italian: "Inizia",
            .portuguese: "Começar",
            .romanian: "Începeți",
            .japanese: "始める",
            .korean: "시작하기",
            .vietnamese: "Bắt đầu",
            .tagalog: "Magsimula",
            .thai: "เริ่มต้นใช้งาน"
        ],
        "how_left_desc": [
            .pirate: "Anchored operates quietly like a trusted navigator, tracking your progress and shielding your attention during your voyage.",
            .english: "Anchored operates quietly in the background, tracking your progress and shielding your attention during work hours.",
            .chinese: "Anchored 在后台静默运行，在工作时间内跟踪您的进度并保护您的注意力。",
            .spanishLA: "Anchored funciona silenciosamente en segundo plano, siguiendo tu progreso y protegiendo tu atención durante las horas de trabajo.",
            .spanishES: "Anchored funciona silenciosamente en segundo plano, siguiendo tu progreso y protegiendo tu atención durante las horas de trabajo.",
            .hindi: "Anchored पृष्ठभूमि में चुपचाप काम करता है, आपकी प्रगति को ट्रैक करता है और काम के घंटों के दौरान आपके ध्यान की रक्षा करता है।",
            .telugu: "యాంకర్డ్ బ్యాక్‌గ్రౌండ్‌లో నిశ్శబ్దంగా పనిచేస్తుంది, మీ పురోగతిని ట్రాక్ చేస్తుంది మరియు పని వేళల్లో మీ దృష్టిని కాపాడుతుంది.",
            .french: "Anchored fonctionne discrètement en arrière-plan, suivant vos progrès et protégeant votre attention pendant vos heures de travail.",
            .italian: "Anchored opera silenziosamente in background, monitorando i tuoi progressi e proteggendo la tua attenzione durante le ore di lavoro.",
            .portuguese: "O Anchored funciona silenciosamente em segundo plano, acompanhando seu progresso e protegendo sua atenção durante o trabalho.",
            .romanian: "Anchored funcționează discret în fundal, urmărindu-vă progresul și protejându-vă atenția în timpul orelor de lucru.",
            .japanese: "Anchoredはバックグラウンドで静かに動作し、作業時間中の進捗を追跡し、集中力を保護します。",
            .korean: "Anchored는 백그라운드에서 조용히 작동하여 작업 시간 동안 진행 상황을 추적하고 주의를 보호합니다.",
            .vietnamese: "Anchored hoạt động thầm lặng trong nền, theo dõi tiến trình và bảo vệ sự tập trung của bạn trong giờ làm việc.",
            .tagalog: "Tahimik na gumagana ang Anchored sa background, sinusubaybayan ang iyong pag-unlad at pinoprotektahan ang iyong focus sa oras ng trabaho.",
            .thai: "Anchored ทำงานอย่างเงียบ ๆ อยู่เบื้องหลัง ช่วยบันทึกความคืบหน้าและปกป้องสมาธิของคุณในระหว่างการทำงาน"
        ],
        "how_card1_title": [
            .pirate: "1. Passive Lookout",
            .english: "1. Passive Monitoring",
            .chinese: "1. 被动监控",
            .spanishLA: "1. Monitoreo Pasivo",
            .spanishES: "1. Supervisión Pasiva",
            .hindi: "1. निष्क्रिय निगरानी",
            .telugu: "1. నిష్క్రియ పర్యవేక్షణ",
            .french: "1. Surveillance passive",
            .italian: "1. Monitoraggio passivo",
            .portuguese: "1. Monitoramento Passivo",
            .romanian: "1. Monitorizare pasivă",
            .japanese: "1. バックグラウンド監視",
            .korean: "1. 백그라운드 모니터링",
            .vietnamese: "1. Giám sát Thụ động",
            .tagalog: "1. Pasibong Pagsubaybay",
            .thai: "1. ระบบเฝ้าดูเบื้องหลัง"
        ],
        "how_card2_title": [
            .pirate: "2. Drop the Anchor",
            .english: "2. Focus Sessions",
            .chinese: "2. 专注会话",
            .spanishLA: "2. Sesiones de Enfoque",
            .spanishES: "2. Sesiones de Concentración",
            .hindi: "2. फोकस सत्र",
            .telugu: "2. ఫోకస్ సెషన్లు",
            .french: "2. Sessions de travail",
            .italian: "2. Sessioni di concentrazione",
            .portuguese: "2. Sessões de Foco",
            .romanian: "2. Sesiuni de concentrare",
            .japanese: "2. フォーカスセッション",
            .korean: "2. 집중 세션 시작",
            .vietnamese: "2. Phiên Tập trung",
            .tagalog: "2. Focus Session",
            .thai: "2. ช่วงเวลาการทำงาน"
        ],
        "how_card3_title": [
            .pirate: "3. Ocean Fog (Dimming)",
            .english: "3. Screen Dimming",
            .chinese: "3. 屏幕变暗",
            .spanishLA: "3. Atenuación de Pantalla",
            .spanishES: "3. Oscurecimiento de Pantalla",
            .hindi: "3. स्क्रीन का धीमा होना",
            .telugu: "3. స్క్రీన్ మసకబారడం",
            .french: "3. Assombrissement de l'écran",
            .italian: "3. Oscuramento dello schermo",
            .portuguese: "3. Escurecimento da Tela",
            .romanian: "3. Întunecarea ecranului",
            .japanese: "3. 画面の減光",
            .korean: "3. 화면 어두워짐",
            .vietnamese: "3. Làm mờ Màn hình",
            .tagalog: "3. Pagdidilim ng Screen",
            .thai: "3. การหรี่แสงหน้าจอ"
        ],
        "how_title": [
            .pirate: "Rules of the Sea",
            .english: "How It Works",
            .chinese: "工作原理",
            .spanishLA: "Cómo Funciona",
            .spanishES: "Cómo Funciona",
            .hindi: "यह कैसे काम करता है",
            .telugu: "ఇది ఎలా పనిచేస్తుంది",
            .french: "Comment ça marche",
            .italian: "Come funziona",
            .portuguese: "Como Funciona",
            .romanian: "Cum funcționează",
            .japanese: "仕組みについて",
            .korean: "작동 방식",
            .vietnamese: "Cách hoạt động",
            .tagalog: "Paano Ito Gumagana",
            .thai: "วิธีการทำงาน"
        ],
        "how_desc1": [
            .pirate: "We monitor browser domains and apps. Only active focus counts as sailing.",
            .english: "We track browser domains and application usage. Only active productive tasks count towards your focus session.",
            .chinese: "我们追踪浏览器域名和应用程序使用情况。只有处于活跃的工作任务才会计入您的专注时间。",
            .spanishLA: "Realizamos un seguimiento de los dominios de navegación y el uso de aplicaciones. Solo las tareas productivas activas cuentan para tu enfoque.",
            .spanishES: "Hacemos seguimiento de dominios del navegador y uso de aplicaciones. Solo el trabajo productivo activo cuenta como concentración.",
            .hindi: "हम ब्राउज़र डोमेन और ऐप उपयोग को ट्रैक करते हैं। केवल सक्रिय उत्पादक कार्य ही आपके फोकस सत्र में गिने जाते हैं।",
            .telugu: "మేము బ్రౌజర్ డొమైన్‌లు మరియు యాప్ వినియోగాన్ని ట్రాక్ చేస్తాము. క్రియాశీల ఉత్పాదక పనులు మాత్రమే మీ ఫోకస్ సెషన్‌లో లెక్కించబడతాయి.",
            .french: "Nous suivons les domaines de navigation et l'utilisation des applications. Seules les tâches productives actives comptent pour votre session.",
            .italian: "Monitoriamo i domini web e l'uso delle app. Solo il lavoro effettivamente produttivo viene conteggiato nella sessione di concentrazione.",
            .portuguese: "Rastreamos domínios do navegador e uso de aplicativos. Apenas tarefas produtivas ativas contam para a sua sessão.",
            .romanian: "Urmărim domeniile browserului și utilizarea aplicațiilor. Doar sarcinile productive active contează pentru sesiunea dvs.",
            .japanese: "ブラウザのドメインとアプリの使用状況を追跡します。アクティブな生産的タスクのみがフォーカスセッションとしてカウントされます。",
            .korean: "브라우저 도메인과 앱 사용량을 추적합니다. 활성화된 생산적 작업만 집중 세션에 반영됩니다.",
            .vietnamese: "Chúng tôi theo dõi các tên miền trình duyệt và mức sử dụng ứng dụng. Chỉ những tác vụ làm việc tích cực mới được tính vào phiên tập trung.",
            .tagalog: "Sinusubaybayan namin ang mga domain ng browser at paggamit ng app. Mga produktibong gawain lang ang binibilang sa iyong session.",
            .thai: "เราตรวจจับความเคลื่อนไหวบนเว็บบราวเซอร์และแอปพลิเคชัน โดยจะนับเวลาเฉพาะเมื่อคุณตั้งใจทำงานจริง ๆ เท่านั้น"
        ],
        "how_desc2": [
            .pirate: "If you spend too long in distracting apps, the fog rolls in (screens dim) to nudge you back.",
            .english: "If you spend too much time on distracting applications, screen dimming will activate to nudge you back to work.",
            .chinese: "如果您在分心应用上停留太久，屏幕将会变暗，以督促您重新回到工作中。",
            .spanishLA: "Si pasas demasiado tiempo en aplicaciones de distracción, la pantalla se atenuará para recordarte que vuelvas al trabajo.",
            .spanishES: "Si pasas demasiado tiempo en aplicaciones de distracción, la pantalla se oscurecerá para incitarte a volver al trabajo.",
            .hindi: "यदि आप ध्यान भटकाने वाले ऐप्स पर बहुत अधिक समय बिताते हैं, तो स्क्रीन धीमी हो जाएगी ताकि आप काम पर वापस लौट सकें।",
            .telugu: "మీరు దృష్టిని మరల్చే యాప్‌లలో ఎక్కువ సమయం గడిపితే, మిమ్మల్ని తిరిగి పనిలోకి నడిపించడానికి స్క్రీన్ మసకబారుతుంది.",
            .french: "Si vous passez trop de temps sur des applications distrayantes, l'écran s'assombrira pour vous inciter à vous remettre au travail.",
            .italian: "Se trascorri troppo tempo sulle app che distraggono, lo schermo si oscurerà per spingerti a tornare al lavoro.",
            .portuguese: "Se você passar muito tempo em aplicativos de distração, a tela escurecerá para lembrá-lo de voltar ao trabalho.",
            .romanian: "Dacă petreceți prea mult timp pe aplicații care vă distrag atenția, ecranul se va întuneca pentru a vă readuce la lucru.",
            .japanese: "気を散らすアプリに時間を費やしすぎると、画面が暗くなり、作業に戻るよう促します。",
            .korean: "집중을 방해하는 앱에서 시간을 너무 많이 보내면 화면이 어두워지며 작업으로 돌아가도록 유도합니다.",
            .vietnamese: "Nếu bạn dành quá nhiều thời gian cho các ứng dụng gây xao nhãng, màn hình sẽ mờ đi để nhắc nhở bạn quay lại làm việc.",
            .tagalog: "Kung gumugol ka ng masyadong maraming oras sa mga nakaka-distract na app, magdidilim ang screen upang akayin ka pabalik sa trabaho.",
            .thai: "หากคุณใช้งานแอปพลิเคชันที่ดึงสมาธิของคุณนานเกินไป หน้าจอจะเริ่มหรี่แสงลงเพื่อเตือนให้คุณกลับไปทำงาน"
        ],
        "how_desc3": [
            .pirate: "Return to your work app or enter focus duration to lift the anchor.",
            .english: "Return to your productive application or select a focus duration to restore full brightness.",
            .chinese: "返回您的工作应用或选择专注时长，即可恢复屏幕亮度。",
            .spanishLA: "Regresa a tu aplicación de trabajo o selecciona una duración de enfoque para restaurar el brillo de la pantalla.",
            .spanishES: "Vuelve a tu aplicación de trabajo o introduce un tiempo de concentración para restaurar el brillo.",
            .hindi: "पूर्ण चमक बहाल करने के लिए अपने काम वाले ऐप पर लौटें या फोकस अवधि चुनें।",
            .telugu: "పూర్తి ప్రకాశాన్ని పునరుద్ధరించడానికి మీ పని యాప్‌కి తిరిగి వెళ్లండి లేదా ఫోకస్ సమయాన్ని ఎంచుకోండి.",
            .french: "Retournez sur votre application de travail ou sélectionnez une durée de concentration pour rétablir la luminosité.",
            .italian: "Torna alla tua app di lavoro o seleziona una durata di concentrazione per ripristinare la luminosità dello schermo.",
            .portuguese: "Retorne ao seu aplicativo de trabalho ou selecione uma duração de foco para restaurar o brilho total.",
            .romanian: "Reveniți la aplicația de lucru sau selectați o durată de concentrare pentru a restabili luminozitatea completă.",
            .japanese: "作業用のアプリに戻るか、フォーカス時間を設定することで、画面の明るさが元に戻ります。",
            .korean: "작업 중이던 앱으로 돌아가거나 집중 시간을 설정하면 화면 밝기가 복원됩니다.",
            .vietnamese: "Quay lại ứng dụng công việc của bạn hoặc chọn thời gian tập trung để khôi phục độ sáng màn hình.",
            .tagalog: "Bumalik sa iyong productive app o magtakda ng tagal ng focus upang ibalik ang buong liwanag ng screen.",
            .thai: "กลับไปที่แอปพลิเคชันทำงานของคุณ หรือระบุเวลาที่ต้องการตั้งใจทำงานเพื่อคืนความสว่างของหน้าจอตามปกติ"
        ],
        "how_btn": [
            .pirate: "Chart the Course",
            .english: "Continue",
            .chinese: "继续",
            .spanishLA: "Continuar",
            .spanishES: "Continuar",
            .hindi: "आगे बढ़ें",
            .telugu: "కొనసాగించండి",
            .french: "Continuer",
            .italian: "Continua",
            .portuguese: "Continuar",
            .romanian: "Continuați",
            .japanese: "続行する",
            .korean: "계속하기",
            .vietnamese: "Tiếp tục",
            .tagalog: "Ipagpatuloy",
            .thai: "ดำเนินการต่อ"
        ],
        "focus_title": [
            .pirate: "Focus Vessels",
            .english: "Focus Applications",
            .chinese: "专注应用",
            .spanishLA: "Aplicaciones de Enfoque",
            .spanishES: "Aplicaciones de Enfoque",
            .hindi: "फोकस ऐप्स",
            .telugu: "ఫోకస్ అప్లికేషన్లు",
            .french: "Applications de travail",
            .italian: "Applicazioni di lavoro",
            .portuguese: "Aplicativos de Foco",
            .romanian: "Aplicații de lucru",
            .japanese: "フォーカス対象アプリ",
            .korean: "집중할 앱 선택",
            .vietnamese: "Ứng dụng Tập trung",
            .tagalog: "Mga Focus App",
            .thai: "แอปพลิเคชันเพื่อการทำงาน"
        ],
        "focus_desc": [
            .pirate: "Only selected applications count as active voyages. Neutral and background apps won't accumulate focus progress, keeping your journey steady.",
            .english: "Only selected applications count towards focus sessions. Other applications will be treated as neutral or background apps.",
            .chinese: "只有选定的应用程序会计入专注时间。其他应用将被视为中立或后台应用。",
            .spanishLA: "Solo las aplicaciones seleccionadas cuentan para tus sesiones de enfoque. Las demás se considerarán neutras o de fondo.",
            .spanishES: "Solo las aplicaciones seleccionadas cuentan para tu concentración. Las demás serán tratadas como neutras o de fondo.",
            .hindi: "केवल चयनित ऐप्स ही फोकस सत्र में गिने जाते हैं। अन्य ऐप्स को सामान्य माना जाएगा।",
            .telugu: "ఎంచుకున్న అప్లికేషన్‌లు మాత్రమే ఫోకస్ సెషన్‌లలో లెక్కించబడతాయి. ఇతర యాప్‌లు తటస్థంగా పరిగణించబడతాయి.",
            .french: "Seules les applications sélectionnées comptent pour vos sessions de concentration. Les autres seront considérées comme neutres.",
            .italian: "Solo le app selezionate contano per le sessioni di concentrazione. Le altre saranno considerate neutre o di sfondo.",
            .portuguese: "Apenas os aplicativos selecionados contam para o foco. Os outros serão tratados como neutros ou de segundo plano.",
            .romanian: "Doar aplicațiile selectate contează pentru sesiunile de concentrare. Celelalte vor fi tratate ca neutre.",
            .japanese: "選択されたアプリのみがフォーカス対象としてカウントされます。その他のアプリはニュートラルまたはバックグラウンドとして処理されます。",
            .korean: "선택한 앱을 사용할 때만 집중 시간으로 기록됩니다. 그 외의 앱은 무시되거나 대기 상태로 처리됩니다.",
            .vietnamese: "Chỉ các ứng dụng được chọn mới tính vào phiên tập trung. Các ứng dụng khác sẽ được coi là trung lập hoặc chạy nền.",
            .tagalog: "Tanging mga napiling app lang ang bibilangin sa focus session. Ang iba ay ituturing na neutral o background app.",
            .thai: "เฉพาะแอปพลิเคชันที่เลือกเท่านั้นที่จะถูกนับเวลาการทำงาน แอปอื่น ๆ จะถือว่าเป็นแอปทั่วไปที่ไม่มีผลต่อเวลาทำงาน"
        ],
        "focus_custom_btn": [
            .pirate: "Commission Custom Vessel...",
            .english: "Add Custom Application...",
            .chinese: "添加自定义应用...",
            .spanishLA: "Añadir Aplicación Personalizada...",
            .spanishES: "Añadir Aplicación Personalizada...",
            .hindi: "कस्टम ऐप जोड़ें...",
            .telugu: "కస్టమ్ యాప్‌ను జోడించండి...",
            .french: "Ajouter une application personnalisée...",
            .italian: "Aggiungi app personalizzata...",
            .portuguese: "Adicionar aplicativo personalizado...",
            .romanian: "Adăugați o aplicație personalizată...",
            .japanese: "カスタムアプリを追加...",
            .korean: "사용자 정의 앱 추가...",
            .vietnamese: "Thêm ứng dụng tùy chỉnh...",
            .tagalog: "Magdagdag ng Custom na App...",
            .thai: "เพิ่มแอปพลิเคชันด้วยตนเอง..."
        ],
        "focus_btn": [
            .pirate: "Secure the Rigging",
            .english: "Confirm Focus Apps",
            .chinese: "确认专注应用",
            .spanishLA: "Confirmar Aplicaciones de Enfoque",
            .spanishES: "Confirmar Aplicaciones de Enfoque",
            .hindi: "फोकस ऐप्स की पुष्टि करें",
            .telugu: "ఫోకస్ యాప్‌లను నిర్ధారించండి",
            .french: "Valider les applications de travail",
            .italian: "Conferma app di lavoro",
            .portuguese: "Confirmar Aplicativos de Foco",
            .romanian: "Confirmați aplicațiile",
            .japanese: "フォーカスアプリを確定する",
            .korean: "선택한 앱 저장",
            .vietnamese: "Xác nhận Ứng dụng Tập trung",
            .tagalog: "Kumpirmahin ang mga Focus App",
            .thai: "ยืนยันแอปเพื่อการทำงาน"
        ],
        "focus_active_title": [
            .pirate: "ACTIVE FOCUS VESSELS",
            .english: "ACTIVE FOCUS APPLICATIONS",
            .chinese: "当前专注应用",
            .spanishLA: "APLICACIONES DE ENFOQUE ACTIVAS",
            .spanishES: "APLICACIONES DE ENFOQUE ACTIVAS",
            .hindi: "सक्रिय फोकस ऐप्स",
            .telugu: "క్రియాశీల ఫోకస్ అప్లికేషన్లు",
            .french: "APPLICATIONS DE TRAVAIL ACTIVES",
            .italian: "APP DI LAVORO ATTIVE",
            .portuguese: "APLICATIVOS DE FOCO ATIVOS",
            .romanian: "APLICAȚII DE LUCRU ACTIVE",
            .japanese: "アクティブなフォーカスアプリ",
            .korean: "지정된 집중 앱",
            .vietnamese: "ỨNG DỤNG TẬP TRUNG HOẠT ĐỘNG",
            .tagalog: "MGA AKTIBONG FOCUS APP",
            .thai: "แอปพลิเคชันทำงานที่เลือกไว้"
        ],
        "focus_suggest_title": [
            .pirate: "SUGGESTED VESSELS (INSTALLED)",
            .english: "SUGGESTED APPLICATIONS (INSTALLED)",
            .chinese: "推荐的应用程序 (已安装)",
            .spanishLA: "APLICACIONES RECOMENDADAS (INSTALADAS)",
            .spanishES: "APLICACIONES RECOMENDADAS (INSTALADAS)",
            .hindi: "सुझाए गए ऐप्स (इंस्टॉल किए गए)",
            .telugu: "సూచించబడిన అప్లికేషన్లు (ఇన్‌స్టాల్ చేయబడినవి)",
            .french: "APPLICATIONS SUGGÉRÉES (INSTALLÉES)",
            .italian: "APP CONSIGLIATE (INSTALLATE)",
            .portuguese: "APLICATIVOS SUGERIDOS (INSTALADOS)",
            .romanian: "APLICAȚII RECOMANDATE (INSTALATE)",
            .japanese: "推奨アプリ (インストール済み)",
            .korean: "추천 앱 (설치됨)",
            .vietnamese: "ỨNG DỤNG GỢI Ý (ĐÃ CÀI ĐẶT)",
            .tagalog: "MGA REKOMENDADONG APP (NAKA-INSTALL)",
            .thai: "แอปพลิเคชันที่แนะนำ (ติดตั้งแล้ว)"
        ],
        "focus_empty": [
            .pirate: "No focus vessels chartered. Select recommendations below or commission a custom app.",
            .english: "No focus applications selected yet. Choose from the suggestions below or add a custom app.",
            .chinese: "尚未选择专注应用。请从下方推荐中选择或添加自定义应用。",
            .spanishLA: "Aún no has seleccionado aplicaciones de enfoque. Elige entre las sugerencias o añade una personalizada.",
            .spanishES: "No se han seleccionado aplicaciones de enfoque. Elige entre las recomendaciones o añade una personalizada.",
            .hindi: "अभी तक कोई फोकस ऐप नहीं चुना गया है। नीचे दिए गए सुझावों से चुनें या कस्टम ऐप जोड़ें।",
            .telugu: "ఇంకా ఫోకస్ యాప్‌లు ఏవీ ఎంచుకోలేదు. క్రింది సూచనల నుండి ఎంచుకోండి లేదా కస్టమ్ యాప్‌ను జోడించండి.",
            .french: "Aucune application sélectionnée. Choisissez parmi les suggestions ci-dessous ou ajoutez-en une.",
            .italian: "Nessuna applicazione selezionata. Scegli tra i suggerimenti qui sotto o aggiungine una personalizzata.",
            .portuguese: "Nenhum aplicativo de foco selecionado. Escolha entre as sugestões abaixo ou adicione um personalizado.",
            .romanian: "Nicio aplicație selectată. Alegeți din sugestiile de mai jos sau adăugați una personalizată.",
            .japanese: "フォーカスアプリが選択されていません。以下の推奨リストから選択するか、カスタムアプリを追加してください。",
            .korean: "선택된 집중 앱이 없습니다. 아래 추천 목록에서 선택하거나 직접 앱을 추가하세요.",
            .vietnamese: "Chưa chọn ứng dụng tập trung nào. Hãy chọn từ danh sách gợi ý hoặc thêm ứng dụng tùy chỉnh.",
            .tagalog: "Walang napiling focus app. Pumili sa mga rekomendasyon o magdagdag ng custom na app.",
            .thai: "ยังไม่มีการเลือกแอปพลิเคชันเพื่อการทำงาน โปรดเลือกจากแอปแนะนำด้านล่าง หรือเพิ่มแอปด้วยตนเอง"
        ],
        "dist_title": [
            .pirate: "Mutinous Apps",
            .english: "Distraction List",
            .chinese: "分心应用",
            .spanishLA: "Lista de Distracciones",
            .spanishES: "Lista de Distracciones",
            .hindi: "ध्यान भटकाने वाले ऐप्स",
            .telugu: "దృష్టిని మరల్చే అప్లికేషన్లు",
            .french: "Distractions à bloquer",
            .italian: "Applicazioni da bloccare",
            .portuguese: "Lista de Distrações",
            .romanian: "Distrageri de blocat",
            .japanese: "気を散らすアプリリスト",
            .korean: "집중을 방해하는 앱 목록",
            .vietnamese: "Danh sách Xao Nhãng",
            .tagalog: "Listahan ng Distraction",
            .thai: "แอปพลิเคชันที่ดึงความสนใจ"
        ],
        "dist_desc": [
            .pirate: "Blacklist distracting applications and websites. Falling into these waters triggers warning pills and rolls in the dimming fog.",
            .english: "Blacklist distracting applications and websites. Using these will trigger warning countdowns and activate screen dimming.",
            .chinese: "将分心的应用和网站加入黑名单。访问这些内容会触发警告倒计时并使屏幕变暗。",
            .spanishLA: "Bloquea aplicaciones y sitios web que te distraigan. Usarlos activará una cuenta regresiva y atenuará la pantalla.",
            .spanishES: "Añade a la lista negra aplicaciones y webs de distracción. Abrirlas activará una cuenta atrás y oscurecerá la pantalla.",
            .hindi: "ध्यान भटकाने वाले ऐप्स और वेबसाइटों को ब्लॉक करें। इनका उपयोग करने पर चेतावनी टाइमर शुरू होगा और स्क्रीन धीमी हो जाएगी।",
            .telugu: "దృష్టిని మరల్చే అప్లికేషన్‌లు మరియు వెబ్‌సైట్‌లను బ్లాక్‌లిస్ట్‌లో చేర్చండి. వీటిని ఉపయోగిస్తే కౌంట్‌డౌన్ హెచ్చరికలు ప్రారంభమై స్క్రీన్ మసకబారుతుంది.",
            .french: "Bloquez les applications et sites web distrayants. Y accéder lancera un compte à rebours et assombrira l'écran.",
            .italian: "Metti in lista nera le app e i siti che ti distraggono. Aprirli avvierà un conto alla rovescia e oscurerà lo schermo.",
            .portuguese: "Bloqueie aplicativos e sites de distração. Acessá-los iniciará uma contagem regressiva e escurecerá a tela.",
            .romanian: "Adăugați în lista neagră aplicațiile și site-urile care vă distrag atenția. Accesarea lor va activa un ecran întunecat.",
            .japanese: "気を散らすアプリやウェブサイトをブラックリストに登録します。これらを使用すると、警告カウントダウンが開始され、画面が暗くなります。",
            .korean: "집중을 방해하는 앱과 웹사이트를 차단합니다. 이들을 사용하면 경고 카운트다운이 시작되고 화면이 어두워집니다.",
            .vietnamese: "Chặn các ứng dụng và trang web gây xao nhãng. Sử dụng chúng sẽ kích hoạt đếm ngược cảnh báo và làm mờ màn hình.",
            .tagalog: "I-blacklist ang mga nakaka-distract na app at website. Ang paggamit sa mga ito ay magpapasimula ng babala at magpapadilim ng screen.",
            .thai: "บล็อกแอปพลิเคชันและเว็บไซต์ที่ทำลายสมาธิของคุณ การเข้าใช้งานสิ่งเหล่านี้จะเริ่มนับเวลาเตือนและเริ่มหรี่แสงหน้าจอลง"
        ],
        "dist_custom_btn": [
            .pirate: "Log Distracting Ship...",
            .english: "Block Custom Application...",
            .chinese: "拦截自定义应用...",
            .spanishLA: "Bloquear Aplicación Personalizada...",
            .spanishES: "Bloquear Aplicación Personalizada...",
            .hindi: "कस्टम ऐप ब्लॉक करें...",
            .telugu: "కస్టమ్ యాప్‌ను బ్లాక్ చేయండి...",
            .french: "Bloquer une application personnalisée...",
            .italian: "Blocca app personalizzata...",
            .portuguese: "Bloquear aplicativo personalizado...",
            .romanian: "Blocați o aplicație personalizată...",
            .japanese: "カスタムアプリをブロック...",
            .korean: "차단할 앱 직접 추가...",
            .vietnamese: "Chặn ứng dụng tùy chỉnh...",
            .tagalog: "I-block ang Custom na App...",
            .thai: "บล็อกแอปพลิเคชันด้วยตนเอง..."
        ],
        "dist_btn": [
            .pirate: "Lock the Hold",
            .english: "Confirm Distractions",
            .chinese: "确认分心应用",
            .spanishLA: "Confirmar Distracciones",
            .spanishES: "Confirmar Distracciones",
            .hindi: "ब्लॉक ऐप्स की पुष्टि करें",
            .telugu: "బ్లాక్ యాప్‌లను నిర్ధారించండి",
            .french: "Valider les distractions",
            .italian: "Conferma app da bloccare",
            .portuguese: "Confirmar Distrações",
            .romanian: "Confirmați distragerile",
            .japanese: "ブロックアプリを確定する",
            .korean: "차단 앱 저장",
            .vietnamese: "Xác nhận Ứng dụng Xao Nhãng",
            .tagalog: "Kumpirmahin ang mga Distraction",
            .thai: "ยืนยันแอปที่ต้องการบล็อก"
        ],
        "dist_active_title": [
            .pirate: "MUTINUOUS SHIPS",
            .english: "MUTINOUS SHIPS / DISTRACTIONS",
            .chinese: "分心应用程序",
            .spanishLA: "APLICACIONES BLOQUEADAS",
            .spanishES: "APLICACIONES DE DISTRACCIÓN",
            .hindi: "ब्लॉक किए गए ऐप्स",
            .telugu: "బ్లాక్ చేయబడిన అప్లికేషన్లు",
            .french: "DISTRACTIONS ACTIVES",
            .italian: "APP DA BLOCCARE SELEZIONATE",
            .portuguese: "APLICATIVOS BLOQUEADOS",
            .romanian: "DISTRACTIONĂRI DE BLOCAT",
            .japanese: "ブロック対象のアプリ",
            .korean: "차단된 집중 방해 앱",
            .vietnamese: "ỨNG DỤNG BỊ CHẶN",
            .tagalog: "MGA NAKALISTANG DISTRACTION",
            .thai: "แอปพลิเคชันที่ต้องการบล็อก"
        ],
        "dist_suggest_title": [
            .pirate: "SUGGESTED DISTRACTIONS (INSTALLED)",
            .english: "SUGGESTED DISTRACTIONS (INSTALLED)",
            .chinese: "推荐的分心应用 (已安装)",
            .spanishLA: "DISTRACCIONES RECOMENDADAS (INSTALADAS)",
            .spanishES: "DISTRACCIONES RECOMENDADAS (INSTALADAS)",
            .hindi: "सुझाए गए ब्लॉक ऐप्स (इंस्टॉल किए गए)",
            .telugu: "సూచించబడిన బ్లాక్ యాప్‌లు",
            .french: "DISTRACTIONS SUGGÉRÉES (INSTALLÉES)",
            .italian: "APP DA BLOCCARE CONSIGLIATE",
            .portuguese: "DISTRACÕES SUGERIDAS (INSTALADOS)",
            .romanian: "SUGESTII DE DISTRAGERI (INSTALATE)",
            .japanese: "推奨ブロックアプリ (インストール済み)",
            .korean: "추천 차단 앱 (설치됨)",
            .vietnamese: "ỨNG DỤNG XAO NHÃNG GỢI Ý",
            .tagalog: "MGA NAKAKALITONG APP (NAKA-INSTALL)",
            .thai: "แอปพลิเคชันแนะนำที่ควรบล็อก"
        ],
        "dist_empty": [
            .pirate: "No mutinous apps logged. Your deck is clean.",
            .english: "No distractions selected yet. Your list is empty.",
            .chinese: "尚未选择分心应用。您的列表是空的。",
            .spanishLA: "No has seleccionado distracciones aún. Tu lista está vacía.",
            .spanishES: "No se han seleccionado distracciones. Tu lista está limpia.",
            .hindi: "अभी तक कोई ध्यान भटकाने वाला ऐप नहीं चुना गया है।",
            .telugu: "ఇంకా బ్లాక్ యాప్‌లు ఏవీ ఎంచుకోలేదు. మీ లిస్ట్ ఖాళీగా ఉంది.",
            .french: "Aucune distraction sélectionnée. Votre liste est vide.",
            .italian: "Nessuna applicazione da bloccare selezionata. La lista è vuota.",
            .portuguese: "Nenhum aplicativo de distração selecionado. Sua lista está vazia.",
            .romanian: "Nicio distragere selectată. Lista este goală.",
            .japanese: "ブロックするアプリが選択されていません。リストは空です。",
            .korean: "선택된 차단 앱이 없습니다. 목록이 비어 있습니다.",
            .vietnamese: "Chưa chọn ứng dụng gây xao nhãng nào. Danh sách của bạn đang trống.",
            .tagalog: "Walang napiling distraction app. Malinis ang iyong listahan.",
            .thai: "ยังไม่มีการเลือกแอปพลิเคชันที่จะบล็อก รายการของคุณยังว่างอยู่"
        ],
        "pref_title": [
            .pirate: "Command\nDeck",
            .english: "Preferences\nHelm",
            .chinese: "偏好\n设置",
            .spanishLA: "Panel de\nControl",
            .spanishES: "Panel de\nControl",
            .hindi: "प्राथमिकताएं\nकंट्रोल",
            .telugu: "ప్రాధాన్యతలు\nహెల్మ్",
            .french: "Poste de\nCommandement",
            .italian: "Pannello di\nControllo",
            .portuguese: "Painel de\nControle",
            .romanian: "Panou de\nControl",
            .japanese: "環境設定\nコントロール",
            .korean: "설정 및\n조정",
            .vietnamese: "Bảng\nĐiều Khiển",
            .tagalog: "Command\nDeck",
            .thai: "แผงควบคุม\nการตั้งค่า"
        ],
        "pref_desc": [
            .pirate: "Calibrate the helm of your vessel. Set when the anchor triggers, warning countdowns, and automatic sailing settings.",
            .english: "Configure your active preferences. Set when focus session triggers, warn countdowns, and other startup settings.",
            .chinese: "配置您的偏好设置。设置专注会话触发时机、警告倒计时以及其他启动设置。",
            .spanishLA: "Configura tus preferencias activas. Define cuándo se activan las sesiones de enfoque, las cuentas regresivas y otras configuraciones de inicio.",
            .spanishES: "Configura tus preferencias de control. Establece cuándo se inicia la concentración, las cuentas atrás y el arranque automático.",
            .hindi: "अपनी प्राथमिकताएं कॉन्फ़िगर करें। सेट करें कि फोकस सत्र कब शुरू होगा, चेतावनी उलटी गिनती और अन्य स्टार्टअप सेटिंग्स।",
            .telugu: "మీ ప్రాధాన్యతలను కాన్ఫిగర్ చేయండి. ఫోకస్ సెషన్ ఎప్పుడు ప్రారంభించాలో, హెచ్చరిక కౌంట్‌డౌన్‌లు మరియు ఇతర సెట్టింగ్‌లను సెట్ చేయండి.",
            .french: "Configurez vos préférences. Définissez le déclenchement des sessions de travail, les comptes à rebours et le démarrage.",
            .italian: "Configura le tue preferenze. Imposta quando avviare le sessioni, la durata dei conti alla rovescia e l'avvio automatico.",
            .portuguese: "Configure suas preferências. Defina o acionamento das sessões de foco, contagens regressivas de aviso e inicialização.",
            .romanian: "Configurați-vă preferințele active. Setați când pornesc sesiunile, numărătoarea inversă și alte opțiuni de pornire.",
            .japanese: "環境設定を構成します。フォーカスセッションの開始条件、警告のカウントダウン、起動時の設定などを指定します。",
            .korean: "기본 설정을 구성하세요. 집중 세션 시작 기준, 경고 카운트다운 시간 및 기타 시작 설정을 지정합니다.",
            .vietnamese: "Cấu hình các tùy chọn hoạt động của bạn. Thiết lập thời điểm kích hoạt phiên tập trung, đếm ngược cảnh báo và các cài đặt khởi động khác.",
            .tagalog: "I-configure ang iyong mga kagustuhan. Itakda kung kailan magsisimula ang focus session, countdown ng babala, at startup settings.",
            .thai: "ปรับแต่งการตั้งค่าการใช้งาน กำหนดเงื่อนไขการเริ่มตรวจจับความตั้งใจ เวลาเตือน และการเปิดโปรแกรมอัตโนมัติ"
        ],
        "pref_btn": [
            .pirate: "Confirm Settings & Continue",
            .english: "Confirm Settings & Continue",
            .chinese: "确认设置并继续",
            .spanishLA: "Confirmar Ajustes y Continuar",
            .spanishES: "Confirmar Ajustes y Continuar",
            .hindi: "सेटिंग्स की पुष्टि करें और आगे बढ़ें",
            .telugu: "సెట్టింగులను నిర్ధారించి కొనసాగించండి",
            .french: "Confirmer et continuer",
            .italian: "Conferma impostazioni e continua",
            .portuguese: "Confirmar Configurações e Continuar",
            .romanian: "Confirmați și continuați",
            .japanese: "設定を確定して続行する",
            .korean: "설정 저장 후 계속",
            .vietnamese: "Xác nhận Cài đặt & Tiếp tục",
            .tagalog: "Kumpirmahin ang Settings at Ituloy",
            .thai: "ยืนยันการตั้งค่าและดำเนินการต่อ"
        ],
        "pref_threshold_title": [
            .pirate: "Watch Time to Drop Anchor",
            .english: "Focus Trigger Threshold",
            .chinese: "触发专注阈值",
            .spanishLA: "Umbral de Inicio de Enfoque",
            .spanishES: "Umbral de Activación de Concentración",
            .hindi: "फोकस ट्रिगर सीमा",
            .telugu: "ఫోకస్ ట్రిగ్గర్ థ్రెషోల్డ్",
            .french: "Seuil de déclenchement du focus",
            .italian: "Soglia di attivazione concentrazione",
            .portuguese: "Limite de Ativação do Foco",
            .romanian: "Pragul de declanșare a concentrării",
            .japanese: "フォーカス開始のしきい値",
            .korean: "집중 감지 시간 기준",
            .vietnamese: "Ngưỡng Kích hoạt Tập trung",
            .tagalog: "Treshold para sa Pagsisimula ng Focus",
            .thai: "ระยะเวลาที่ใช้เริ่มระบบการทำงาน"
        ],
        "pref_threshold_desc": [
            .pirate: "Sailing time required to trigger anchor.",
            .english: "Time in focus applications required before an active session is established.",
            .chinese: "在活跃专注会话开始前，在专注应用中所需的累积时间。",
            .spanishLA: "Tiempo requerido en aplicaciones de enfoque antes de establecer una sesión activa.",
            .spanishES: "Tiempo requerido en aplicaciones de concentración antes de iniciar una sesión.",
            .hindi: "सक्रिय सत्र स्थापित होने से पहले फोकस ऐप्स में आवश्यक समय।",
            .telugu: "క్రియాశీల సెషన్ ప్రారంభించడానికి ముందు ఫోకస్ అప్లికేషన్‌లలో అవసరమైన సమయం.",
            .french: "Temps d'utilisation requis dans les applications de travail avant le démarrage d'une session.",
            .italian: "Tempo necessario sulle app di lavoro prima di avviare una sessione attiva.",
            .portuguese: "Tempo necessário nos aplicativos de foco antes que uma sessão ativa seja iniciada.",
            .romanian: "Timpul necesar în aplicațiile de lucru înainte de a stabili o sesiune activă.",
            .japanese: "アクティブなフォーカスセッションが確立されるまでに必要な、フォーカスアプリの使用時間です。",
            .korean: "집중 앱 사용 시 활성 세션이 시작되기까지 필요한 감지 시간입니다.",
            .vietnamese: "Thời gian hoạt động trong ứng dụng tập trung cần thiết trước khi một phiên hoạt động được thiết lập.",
            .tagalog: "Oras na kinakailangan sa mga focus app bago magsimula ang isang aktibong session.",
            .thai: "ระยะเวลาที่ต้องใช้งานแอปหลักต่อเนื่อง ก่อนเริ่มบันทึกเวลาทำงาน"
        ],
        "pref_countdown_title": [
            .pirate: "Seconds Before Fog Rolls In",
            .english: "Countdown Before Blocking",
            .chinese: "拦截前的倒计时",
            .spanishLA: "Tiempo de Advertencia antes del Bloqueo",
            .spanishES: "Cuenta atrás antes de Oscurecer",
            .hindi: "ब्लॉक करने से पहले उलटी गिनती",
            .telugu: "బ్లాక్ చేయడానికి ముందు కౌంట్‌డౌన్",
            .french: "Délai de grâce avant assombrissement",
            .italian: "Conto alla rovescia prima del blocco",
            .portuguese: "Contagem Regressiva antes do Bloqueio",
            .romanian: "Numărătoarea inversă înainte de blocare",
            .japanese: "ブロック前のカウントダウン",
            .korean: "차단 전 경고 대기 시간",
            .vietnamese: "Đếm ngược Trước khi Chặn",
            .tagalog: "Countdown Bago I-block",
            .thai: "เวลานับถอยหลังก่อนเริ่มบล็อก"
        ],
        "pref_countdown_desc": [
            .pirate: "Seconds allowed in mutinous apps before dimming.",
            .english: "Grace period (seconds) allowed in distracted apps before screen dimming is active.",
            .chinese: "在屏幕变暗之前，允许在分心应用中停留的宽限时间 (秒)。",
            .spanishLA: "Periodo de gracia (segundos) permitido en aplicaciones de distracción antes de atenuar la pantalla.",
            .spanishES: "Período de gracia (segundos) permitido en aplicaciones de distracción antes de oscurecer la pantalla.",
            .hindi: "स्क्रीन धीमी होने से पहले ध्यान भटकाने वाले ऐप्स में अनुमत समय (सेकंड)।",
            .telugu: "స్క్రీన్ మసకబారడానికి ముందు దృష్టిని మరల్చే యాప్‌లలో అనుమతించబడే సమయం (సెకన్లు).",
            .french: "Temps de tolérance (secondes) accordé dans les distractions avant l'assombrissement de l'écran.",
            .italian: "Periodo di tolleranza (in secondi) sulle app di distrazione prima che lo schermo si oscuri.",
            .portuguese: "Tempo de tolerância (segundos) permitido em aplicativos de distração antes de escurecer a tela.",
            .romanian: "Perioada de grație (secunde) permisă în aplicațiile care distrag atenția înainte ca ecranul să se întunece.",
            .japanese: "画面が暗くなる前に、気を散らすアプリの使用を許容する猶予時間 (秒) です。",
            .korean: "집중을 방해하는 앱 사용 시 화면이 어두워지기 전까지 허용되는 유예 시간(초)입니다.",
            .vietnamese: "Thời gian ân hạn (giây) được phép trong ứng dụng xao nhãng trước khi màn hình mờ đi.",
            .tagalog: "Palugit (segundo) na pinapayagan sa mga nakaka-distract na app bago magdilim ang screen.",
            .thai: "ระยะเวลาผ่อนผัน (วินาที) ในการใช้งานแอปอื่น ก่อนที่หน้าจอจะหรี่แสงลง"
        ],
        "pref_launch_title": [
            .pirate: "Hoist Sails on Startup",
            .english: "Launch at Login",
            .chinese: "开机自启动",
            .spanishLA: "Iniciar al Encender",
            .spanishES: "Arrancar al Iniciar Sesión",
            .hindi: "लॉगिन पर शुरू करें",
            .telugu: "లాగిన్ వద్ద ప్రారంభించండి",
            .french: "Lancer au démarrage",
            .italian: "Avvia al login",
            .portuguese: "Iniciar ao Fazer Login",
            .romanian: "Lansați la pornire",
            .japanese: "ログイン時に起動",
            .korean: "로그인 시 자동 실행",
            .vietnamese: "Khởi động cùng Hệ thống",
            .tagalog: "Ilunsad sa Pag-login",
            .thai: "เปิดใช้งานอัตโนมัติเมื่อเข้าสู่ระบบ"
        ],
        "pref_launch_desc": [
            .pirate: "Automatically launch Anchored and begin your voyage when you log in.",
            .english: "Automatically launch Anchored and start monitoring when you log in to your Mac.",
            .chinese: "登录 Mac 时自动启动 Anchored 并开始监控。",
            .spanishLA: "Inicia automáticamente Anchored y comienza la supervisión cuando inicies sesión en tu Mac.",
            .spanishES: "Inicia Anchored automáticamente y activa el control al arrancar tu Mac.",
            .hindi: "जब आप अपने मैक पर लॉग इन करते हैं तो स्वचालित रूप से Anchored लॉन्च करें और निगरानी शुरू करें।",
            .telugu: "మీరు మీ మ్యాక్‌లోకి లాగిన్ అయినప్పుడు స్వయంచాలకంగా యాంకర్డ్‌ను ప్రారంభించి, పర్యవేక్షణను ప్రారంభించండి.",
            .french: "Lance automatiquement Anchored et démarre la surveillance à l'ouverture de session sur votre Mac.",
            .italian: "Avvia automaticamente Anchored e attiva il monitoraggio al login sul Mac.",
            .portuguese: "Inicia automaticamente o Anchored e começa a monitorar quando você faz login no Mac.",
            .romanian: "Lansați automat Anchored și începeți monitorizarea când vă conectați la Mac.",
            .japanese: "Macにログインしたときに自動的にAnchoredを起動し、監視を開始します。",
            .korean: "Mac에 로그인할 때 Anchored를 자동으로 실행하고 모니터링을 시작합니다.",
            .vietnamese: "Tự động khởi động Anchored và bắt đầu theo dõi khi bạn đăng nhập vào Mac.",
            .tagalog: "Awtomatikong ilunsad ang Anchored at simulan ang pagsubaybay kapag nag-login sa iyong Mac.",
            .thai: "เปิดใช้งาน Anchored และเริ่มต้นระบบโดยอัตโนมัติเมื่อคุณเข้าสู่ระบบ Mac"
        ],
        "pref_nudges_title": [
            .pirate: "Enable Scout Sentinels (Smart Nudges)",
            .english: "Enable Smart Nudges",
            .chinese: "启用智能微调提醒",
            .spanishLA: "Activar Alertas Inteligentes",
            .spanishES: "Activar Nudges Inteligentes",
            .hindi: "स्मार्ट नज सक्षम करें",
            .telugu: "స్మార్ట్ నడ్జ్‌లను ప్రారంభించండి",
            .french: "Activer les notifications intelligentes",
            .italian: "Attiva suggerimenti intelligenti",
            .portuguese: "Ativar Avisos Inteligentes",
            .romanian: "Activați Nudges Inteligente",
            .japanese: "スマートナッジを有効にする",
            .korean: "스마트 알림(Nudge) 활성화",
            .vietnamese: "Bật Cảnh báo Thông minh",
            .tagalog: "I-enable ang Smart Nudges",
            .thai: "เปิดใช้งานระบบการสะกิดเตือนอัจฉเบรีย"
        ],
        "pref_nudges_desc": [
            .pirate: "Send scout warnings if background activities indicate distraction patterns.",
            .english: "Receive smart warnings if active background applications indicate potential distraction patterns.",
            .chinese: "当后台应用程序活动显示潜在分心迹象时，向您发送智能提醒。",
            .spanishLA: "Recibe alertas si las aplicaciones en segundo plano indican posibles patrones de distracción.",
            .spanishES: "Recibe avisos si las aplicaciones en segundo plano muestran patrones de distracción potencial.",
            .hindi: "यदि सक्रिय बैकग्राउंड ऐप्स संभावित ध्यान भटकाने के पैटर्न का संकेत देते हैं तो स्मार्ट चेतावनियां प्राप्त करें।",
            .telugu: "యాక్టివ్ బ్యాక్‌గ్రౌండ్ అప్లికేషన్‌లు దృష్టిని మరల్చే అవకాశం ఉందని సూచించినప్పుడు స్మార్ట్ హెచ్చరికలను పొందండి.",
            .french: "Recevez des alertes intelligentes si les applications en arrière-plan suggèrent des distractions potentielles.",
            .italian: "Ricevi avvisi se le applicazioni in background mostrano potenziali fonti di distrazione.",
            .portuguese: "Receba alertas inteligentes se os aplicativos em segundo plano indicarem possíveis distrações.",
            .romanian: "Primiți avertismente dacă aplicațiile din fundal indică un comportament de distragere.",
            .japanese: "バックグラウンドのアプリ使用状況から、気が散る予兆を検出してスマートに警告します。",
            .korean: "대기 상태의 앱 동작 분석을 통해 집중이 분산될 우려가 있을 때 스마트 알림을 보냅니다.",
            .vietnamese: "Nhận cảnh báo thông minh nếu các ứng dụng chạy nền hoạt động cho thấy dấu hiệu xao nhãng tiềm ẩn.",
            .tagalog: "Makatanggap ng babala kung ang background apps ay nagpapakita ng potensyal na nakakagambalang paggamit.",
            .thai: "ส่งการเตือนอัจฉริยะเมื่อตรวจพบแนวโน้มการใช้งานแอปพลิเคชันอื่นที่จะทำให้คุณเสียสมาธิ"
        ],
        "perm_title": [
            .pirate: "Unlock the\nSpyglass",
            .english: "Grant\nPermissions",
            .chinese: "授予\n权限",
            .spanishLA: "Otorgar\nPermisos",
            .spanishES: "Otorgar\nPermisos",
            .hindi: "अनुमति\nदें",
            .telugu: "అనుమతులు\nఇవ్వండి",
            .french: "Autoriser les\nAccès",
            .italian: "Concedi\nPermessi",
            .portuguese: "Conceder\nPermissões",
            .romanian: "Acordați\nPermisiuni",
            .japanese: "アクセス権限を\n許可する",
            .korean: "권한\n허용",
            .vietnamese: "Cấp\nQuyền Truy Cập",
            .tagalog: "Ipagkaloob ang\nPermiso",
            .thai: "อนุญาต\nการเข้าถึง"
        ],
        "perm_desc": [
            .pirate: "Anchored requires Accessibility permissions to monitor browser domains and window titles. This allows us to detect when you wander into distracting waters and gently guide you back.",
            .english: "Anchored requires Accessibility permissions to monitor browser domains and window titles. This allows us to detect when you wander into distracting websites and apps.",
            .chinese: "Anchored 需要辅助功能权限来监控浏览器域名和窗口标题。这使我们能够检测您何时分心，并引导您重新专注。",
            .spanishLA: "Anchored requiere permisos de Accesibilidad para supervisar los dominios del navegador y los títulos de las ventanas, lo que nos permite detectar distracciones.",
            .spanishES: "Anchored requiere permisos de Accesibilidad para monitorizar los dominios del navegador y los títulos de las ventanas, permitiendo detectar cuándo te distraes.",
            .hindi: "Anchored को ब्राउज़र डोमेन और विंडो शीर्षकों की निगरानी के लिए एक्सेसिबिलिटी अनुमतियों की आवश्यकता होती है ताकि ध्यान भटकने पर रोका जा सके।",
            .telugu: "బ్రౌజర్ డొమైన్‌లు మరియు విండో శీర్ศికలను పర్యవేక్షించడానికి యాంకర్డ్‌కు యాక్సెసిబిలిటీ అనుమతులు అవసరం.",
            .french: "Anchored nécessite des autorisations d'accessibilité pour surveiller les domaines du navigateur et les titres de fenêtres afin de détecter les distractions.",
            .italian: "Anchored richiede i permessi di Accessibilità per monitorare i domini del browser e i titoli delle finestre, consentendo di rilevare le distrazioni.",
            .portuguese: "O Anchored requer permissões de Acessibilidade para monitorar domínios do navegador e títulos de janelas, permitindo detectar distrações.",
            .romanian: "Anchored necesită permisiuni de Accesibilitate pentru a monitoriza domeniile browserului și titlurile ferestrelor pentru a detecta distragerile.",
            .japanese: "ブラウザのドメインやウィンドウのタイトルを監視するために、アクセシビリティの権限が必要です。これにより、気を散らすアプリの使用を検出します。",
            .korean: "브라우저 도메인과 창 제목을 모니터링하려면 접근성 권한이 필요합니다. 이를 통해 집중이 분산되는 상황을 감지할 수 있습니다.",
            .vietnamese: "Anchored yêu cầu quyền Trợ năng để theo dõi các tên miền trình duyệt và tiêu đề cửa sổ, giúp phát hiện khi bạn bị xao nhãng.",
            .tagalog: "Kailangan ng Anchored ng mga permiso sa Accessibility upang subaybayan ang mga domain ng browser at pamagat ng window.",
            .thai: "Anchored จำเป็นต้องได้รับการอนุญาตการเข้าถึง (Accessibility) เพื่อเฝ้าดูเว็บบราวเซอร์และแอปพลิเคชันที่คุณใช้งาน"
        ],
        "perm_btn_grant": [
            .pirate: "Grant Spyglass Access",
            .english: "Grant Accessibility Permission",
            .chinese: "授予辅助功能权限",
            .spanishLA: "Otorgar Permiso de Accesibilidad",
            .spanishES: "Otorgar Permiso de Accesibilidad",
            .hindi: "एक्सेसिबिलिटी अनुमति दें",
            .telugu: "యాక్సెసిబిలిటీ అనుమతి ఇవ్వండి",
            .french: "Autoriser l'accessibilité",
            .italian: "Concedi permessi di Accessibilità",
            .portuguese: "Conceder Permissão de Acessibilidade",
            .romanian: "Acordați permisiunea de accesibilitate",
            .japanese: "アクセシビリティ権限を許可",
            .korean: "접근성 권한 허용하기",
            .vietnamese: "Cấp Quyền Trợ Năng",
            .tagalog: "Ipagkaloob ang Permiso sa Accessibility",
            .thai: "อนุญาตสิทธิ์การเข้าถึง"
        ],
        "perm_btn_continue": [
            .pirate: "Continue Voyage",
            .english: "Continue",
            .chinese: "继续",
            .spanishLA: "Continuar",
            .spanishES: "Continuar",
            .hindi: "आगे बढ़ें",
            .telugu: "కొనసాగించండి",
            .french: "Continuer",
            .italian: "Continua",
            .portuguese: "Continuar",
            .romanian: "Continuați",
            .japanese: "続行する",
            .korean: "계속하기",
            .vietnamese: "Tiếp tục",
            .tagalog: "Ipagpatuloy",
            .thai: "ดำเนินการต่อ"
        ],
        "perm_status_locked": [
            .pirate: "Status: Locked 🔒",
            .english: "Status: Locked 🔒",
            .chinese: "状态：已锁定 🔒",
            .spanishLA: "Estado: Bloqueado 🔒",
            .spanishES: "Estado: Bloqueado 🔒",
            .hindi: "स्थिति: लॉक 🔒",
            .telugu: "స్థితి: లాక్ చేయబడింది 🔒",
            .french: "Statut : Verrouillé 🔒",
            .italian: "Stato: Bloccato 🔒",
            .portuguese: "Status: Bloqueado 🔒",
            .romanian: "Stare: Blocat 🔒",
            .japanese: "ステータス: 未許可 🔒",
            .korean: "상태: 차단됨 🔒",
            .vietnamese: "Trạng thái: Bị khóa 🔒",
            .tagalog: "Katayuan: Naka-lock 🔒",
            .thai: "สถานะ: ล็อกอยู่ 🔒"
        ],
        "perm_status_unlocked": [
            .pirate: "Status: Unlocked 🔓",
            .english: "Status: Granted 🔓",
            .chinese: "状态：已授予 🔓",
            .spanishLA: "Estado: Otorgado 🔓",
            .spanishES: "Estado: Permitido 🔓",
            .hindi: "स्थिति: स्वीकृत 🔓",
            .telugu: "స్థితి: అనుమతించబడింది 🔓",
            .french: "Statut : Autorisé 🔓",
            .italian: "Stato: Concesso 🔓",
            .portuguese: "Status: Concedido 🔓",
            .romanian: "Stare: Permis 🔓",
            .japanese: "ステータス: 許可済み 🔓",
            .korean: "상태: 허용됨 🔓",
            .vietnamese: "Trạng thái: Đã cấp quyền 🔓",
            .tagalog: "Katayuan: Pinayagan 🔓",
            .thai: "สถานะ: อนุญาตแล้ว 🔓"
        ],
        "sail_title": [
            .pirate: "Ready to Set Sail!",
            .english: "Ready to Set Sail!",
            .chinese: "准备好启航！",
            .spanishLA: "¡Listos para Zarpar!",
            .spanishES: "¡Listos para Zarpar!",
            .hindi: "यात्रा शुरू करने के लिए तैयार!",
            .telugu: "ప్రయాణానికి సిద్ధంగా ఉండండి!",
            .french: "Prêt à lever l'ancre !",
            .italian: "Pronti a Salpare!",
            .portuguese: "Pronto para Zarpar!",
            .romanian: "Gata de plecare !",
            .japanese: "準備完了！",
            .korean: "출항 준비 완료!",
            .vietnamese: "Sẵn sàng Khởi hành!",
            .tagalog: "Handa Nang Maglayag!",
            .thai: "พร้อมออกเดินทางแล้ว!"
        ],
        "sail_desc": [
            .pirate: "Your vessel is rigged, coordinates locked, and the wind is at your back. Smooth sailing ahead, Captain.",
            .english: "Your application setup is complete, settings are stored, and you are ready to focus. Welcome to Anchored.",
            .chinese: "您的应用程序配置已完成，设置已保存，您已准备好专注工作。欢迎使用 Anchored。",
            .spanishLA: "La configuración de la aplicación está lista, los ajustes se guardaron y estás listo para concentrarte. Bienvenido a Anchored.",
            .spanishES: "La configuración se ha completado con éxito, los ajustes se han guardado y estás listo para concentrarte. Bienvenido a Anchored.",
            .hindi: "आपका ऐप सेटअप पूरा हो गया है, सेटिंग्स सहेज ली गई हैं, और आप ध्यान केंद्रित करने के लिए तैयार हैं। Anchored में आपका स्वागत है।",
            .telugu: "మీ అప్లికేషన్ సెటప్ పూర్తయింది, సెట్టింగ్‌లు సేవ్ చేయబడ్డాయి మరియు మీరు ఏకాగ్రత వహించడానికి సిద్ధంగా ఉన్నారు. యాంకర్డ్‌కు స్వాగతం.",
            .french: "La configuration est terminée, vos paramètres sont enregistrés et vous êtes prêt à vous concentrer. Bienvenue sur Anchored.",
            .italian: "La configurazione è completa, le impostazioni sono salvate e sei pronto a concentrarti. Benvenuto in Anchored.",
            .portuguese: "A configuração está concluída, suas definições foram salvas e você está pronto para se concentrar. Bem-vindo ao Anchored.",
            .romanian: "Configurarea este finalizată, setările sunt salvate și sunteți gata să vă concentrați. Bine ați venit la Anchored.",
            .japanese: "アプリケーションのセットアップが完了し、設定が保存されました。いつでも集中して作業を開始できます。Anchoredへようこそ！",
            .korean: "애플리케이션 설정이 완료되었으며, 이제 집중할 준비가 되었습니다. Anchored를 시작합니다.",
            .vietnamese: "Cài đặt ứng dụng của bạn đã hoàn tất, các tùy chọn đã được lưu trữ và bạn đã sẵn sàng tập trung. Chào mừng đến với Anchored.",
            .tagalog: "Kumpleto na ang setup ng iyong app, naka-save na ang mga setting, at handa ka nang mag-focus. Welcome sa Anchored.",
            .thai: "การติดตั้งแอปพลิเคชันเสร็จสมบูรณ์ บันทึกการตั้งค่าเรียบร้อยแล้ว และคุณพร้อมที่จะเริ่มตั้งใจทำงาน ยินดีต้อนรับสู่ Anchored"
        ],
        "sail_btn": [
            .pirate: "Set Sail!",
            .english: "Begin Voyage!",
            .chinese: "开始使用！",
            .spanishLA: "¡Comenzar!",
            .spanishES: "¡Zarpar!",
            .hindi: "यात्रा शुरू करें!",
            .telugu: "ప్రయాణాన్ని ప్రారంభించండి!",
            .french: "Lever l'ancre !",
            .italian: "Salpa!",
            .portuguese: "Começar!",
            .romanian: "Setați velă!",
            .japanese: "開始する！",
            .korean: "시작하기!",
            .vietnamese: "Bắt đầu!",
            .tagalog: "Simulan ang Paglalayag!",
            .thai: "เริ่มออกเดินทาง!"
        ]
    ]
}

func t(_ key: String) -> String {
    return LanguageManager.shared.translate(key)
}
